name: Build and Push Backend Docker image

on:
  push:
    branches: [ main ]  # ou o branch que quiser monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ felipergrosa }}
          password: ${{ dckr_pat__RGUwc7hm16TnhnYSB81bayVLjk }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: feliperosa/whaticket-backend:latest
